### ISSUE TITLE
MQTT Config for IoBroker

### ISSUE THREAD

**Issue by CoreDi** [horchi/linux-p4d#37]
I´m struggling now the 3rd time with P4D Data to Iobroker, more precise the MQTT.
Also, other Person are struggling with this, like here:
https://forum.iobroker.net/topic/40376/mqtt-anzeige-anpassen (Also a good Example)

Problem:

In IoBroker the Value is written with "Value:" in the WERT Field, for example:
`{"value": 2.0}
`
Because of this, you can´t work directly with this Data and can not be used directly in Scripts / VIS / Webpages and so on.

Some (good) FHEM Example would be (WERT Field).
`20,2
`
And the example before would be:
`2.0`

My suggestion is to create a IOBROKER Config, similar to "_Home-Assistant" - Config Topic_ in the Webinterface.

Changes needs to be done here:

https://github.com/horchi/linux-p4d/blob/master/mqtttest.c

Change Line 102:
`   asprintf(&valueJson, "{ \"value\" : \"%.2f\" }", value);
`
To:
`   asprintf(&valueJson, "{ \"%.2f\" }", value);
`

**Comment by horchi** [comment]
changing mqtttest.c makes no sense until it's only a test tool for my internal tests and it is not used by the p4d at all.

Regarding the JSON Format, the value of a Element is always located behind the ':', before the ':' ist the element name.
The whole JSON structure it's defined by the needs of the project and not for a specific application such as the IO Broker. 

It is also not the stated goal to support dozens of different formats potentially used for further processing applications.

In the medium term I plan to add some kind of templating or script interface for the JSON objects so that you can configure them yourself.
